config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  match '/help', to: 'static_pages#help', via: 'get'

  resources :users
  match '/sign_up', to: 'users#new', via: 'get'

  resources :reviews, only: [:create, :destroy]

  resources :products

  resources :categories do
    member do
      get :products
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, dependent: :destroy

  has_attached_file :img, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/

  default_scope -> { order('created_at DESC') }
  validates :category_id, presence: true
  validates :img, presence: true
  validates :title, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :can_manage?, only: [:new, :edit, :create, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page], :per_page => 6)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = @product.reviews.build
    @reviews = @product.reviews.paginate(page: params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        flash[:success] = 'Product was successfully created.'
        format.html { redirect_to @product }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        flash[:success] = 'Product was successfully updated.'
        format.html { redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    flash[:danger] = 'Product was successfully deleted.'
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :category_id, :img)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, prompt: true %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/products/_product.erb
<div class="block block-small">
  <%= link_to image_tag(product.img :medium), product %>
  <div class="title">
    <%= truncate( product.title, length: 40) %>
  </div>

  <% if admin? %>
    <div>
      <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary btn-sm pull-right' %>
      <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm pull-right' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="row">
      <%= render @products %>
    </div>
  </div>
  <div class="row">
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/products/new.html.erb
<div class="center">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="block">
  <div class="media">
    <div class="media-left">
      <%= image_tag @product.img(:medium) %>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @product.title %></h4>
      <p><%= @product.description %></p>
    </div>
  </div>
  <div class="clearfix">
    <div class="pull-right">
      <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary ' if admin? %>
      <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary ' if admin? %>
      <%= link_to 'Back', products_path, class: 'btn btn-primary ' %>
    </div>
  </div>
</div>
<%= render 'reviews/form' if signed_in? %>

<%= render @reviews %>
<%= will_paginate @reviews, renderer: BootstrapPagination::Rails %>