config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  match '/help', to: 'static_pages#help', via: 'get'

  resources :users
  match '/sign_up', to: 'users#new', via: 'get'

  resources :reviews, only: [:create, :destroy]

  resources :products

  resources :categories do
    member do
      get :products
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :can_manage?, only: :destroy
  before_action :signed_in_user


  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to :back }
      else
        flash[:danger] = @review.errors.full_messages.first
        format.html { redirect_to :back }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:msg, :product_id, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Comment" %><br>
    <%= f.text_area :msg %>
  </div>
  <div class="field hidden">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field hidden">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id,:value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/reviews/_review.erb
<div class="clearfix review-msg">
  <%= review.msg %>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>Product</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.msg %></td>
        <td><%= review.product_id %></td>
        <td><%= review.user_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="center">
  <h1>New Review</h1>

  <%= render 'form' %>

  <%= link_to 'Back', reviews_path %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Msg:</strong>
  <%= @review.msg %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>