config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  match '/help', to: 'static_pages#help', via: 'get'

  resources :users
  match '/sign_up', to: 'users#new', via: 'get'

  resources :reviews, only: [:create, :destroy]

  resources :products

  resources :categories do
    member do
      get :products
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/views/layouts/_footer.erb
<footer class="footer">
  <small>
    <%= link_to "Keystone app", "http://keystoneapptest.herokuapp.com" %>
    by Zhigun Ivan
  </small>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= image_tag "logo.png", alt: "Keystone", id: "logo" %>
      <nav >
        <ul class="nav pull-right navbar-nav navbar-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Users", users_path if admin? %></li>
                <li><%= link_to "Categories", categories_path if admin? %></li>
                <li><%= link_to "Products", products_path if admin? %></li>
                <li><%= link_to "Settings",edit_user_path(current_user) %></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Sign up", sign_up_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_menu_lefty.erb
<div class="col-sm-3">
  <ul class="list-group inverse">
    <%= link_to products_path do %>
      <li class="list-group-item">
        <span class="badge"><%= Product.all.count %></span>
        All categories
      </li>
    <% end %>
    <% Category.all.each do |c| %>
      <%= link_to  products_category_path(c) do %>
        <li class="list-group-item">
          <span class="badge"><%= c.products.count %></span>
          <%= c.name %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to 'New Product', new_product_path, class: 'btn btn-lg btn-primary' if admin? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
    <%= render "layouts/header" %>

    <div class="container-fluid">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}", role: 'alert') %>
      <% end %>
      <div class="jumbotron">
        <div class="row">

          <%= render 'layouts/menu_lefty' if show_left_menu? %>

          <div<%= raw(' class="col-sm-9"') if show_left_menu? %>>
            <%= yield %>
          </div>
        </div>

        <%= render 'layouts/footer' %>
      </div>
    </div>

</body>
</html>